In [1]:
import numpy as np

### 1.Write a NumPy program to find the dot product of two arrays of different dimensions.

In [2]:
# import the random function to generate the random numbers that 
# we will need to create the dimensions of the matrix
import random

i1 = random.randint(1, 5)
j = random.randint(1, 5)
j2 = random.randint(1, 5)

# Note: the matrix multiplicity condition must be maintained
# the number of rows of the first matrix should be equal to the number of columns of the second matrix
# we use j for both
arr1 = np.random.randint(0, 50, (i1 ,j))
arr2 = np.random.randint(0, 50, (j, j2))

print(f'''First original arrays:
{arr1} 
Seconde original arrays:
{arr2}''')

result = np.dot(arr1, arr2)
print(f'''Dot product of the said two arrays:
{result}''')



First original arrays:
[[38 48 12]
 [30 37  8]
 [ 1 42  7]
 [ 7 25 13]
 [10 21 47]] 
Seconde original arrays:
[[11 26 32  8]
 [30 20 22 39]
 [ 0 17  3  1]]
Dot product of the said two arrays:
[[1858 2152 2308 2188]
 [1440 1656 1798 1691]
 [1271  985  977 1653]
 [ 827  903  813 1044]
 [ 740 1479  923  946]]


### 2.Write a NumPy program to create a 3x3 identity matrix and stack it vertically and horizontally with another 3x3 matrix

In [9]:
identity = np.identity(3, dtype=int)
matrix = np.random.randint(0, 50, (3 ,3))

print(f'''Identity Matrix:
{identity}
Random Matrix: 
{matrix}
''')

vertical = np.vstack([identity, matrix])
print(f'''Vertical Stack:
{vertical}''')

horizontal = np.hstack([identity, matrix])

print(f'''Horizontal Stack:
{horizontal}''')

Identity Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Random Matrix: 
[[23 23  3]
 [47 20 36]
 [13 37 36]]

Vertical Stack:
[[ 1  0  0]
 [ 0  1  0]
 [ 0  0  1]
 [23 23  3]
 [47 20 36]
 [13 37 36]]
Horizontal Stack:
[[ 1  0  0 23 23  3]
 [ 0  1  0 47 20 36]
 [ 0  0  1 13 37 36]]


### 3.Write a NumPy program to create a 4x4 array with random values and find the sum of each row.

In [10]:
# creat a random 4x4 array
arr = np.random.rand(4, 4)

# Calculate sum of each row
sum_row = np.sum(arr, axis=1)

print(f"Original array:\n{arr}")

# print sum of each row
print(f"Sum of each row:\n{sum_row}")

Original array:
[[0.01021102 0.76542801 0.08899193 0.03794117]
 [0.12674557 0.73596686 0.27322472 0.84304357]
 [0.79481087 0.47595319 0.87818799 0.58975128]
 [0.76127344 0.71690551 0.13864638 0.07882224]]
Sum of each row:
[0.90257214 1.97898073 2.73870334 1.69564758]


### 4.Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element

In [11]:
# creat a 3x3 array with random values
arr = np.random.rand(3, 3)

# Calculate mean of each row
mean = np.mean(arr, axis=1)
# Calculate result (subtract the mean of each row from each element)
result = arr - mean

print(f"Original array elements:\n{arr}\n")
print(f"Mean of each row:\n{mean}\n")
print(f"Subtract the mean of each row from each element:\n{result}")

Original array elements:
[[0.71290171 0.8486493  0.95549329]
 [0.95784279 0.902665   0.4356793 ]
 [0.93547585 0.03590611 0.2695216 ]]

Mean of each row:
[0.83901477 0.7653957  0.41363452]

Subtract the mean of each row from each element:
[[-0.12611306  0.08325361  0.54185877]
 [ 0.11882802  0.1372693   0.02204478]
 [ 0.09646109 -0.72948959 -0.14411292]]


###  5.Write a NumPy program to create a 3x3 array with random values and subtract the mean of each column from each element.

In [12]:
# creat a 3x3 array with random values
arr = np.random.rand(3, 3)

# Calculate mean of each column
mean = np.mean(arr, axis=0)
# Calculate result (subtract the mean of each column from each element)
result = arr - mean

print(f"Original array elements:\n{arr}\n")
print(f"Mean of each column:\n{mean}\n")
print(f"Subtract the mean of each column from each element:\n{result}")

Original array elements:
[[0.28837198 0.17301243 0.62115664]
 [0.8447691  0.41405306 0.12537153]
 [0.82465528 0.4504209  0.63434326]]

Mean of each column:
[0.65259879 0.3458288  0.46029048]

Subtract the mean of each column from each element:
[[-0.3642268  -0.17281637  0.16086616]
 [ 0.19217031  0.06822426 -0.33491894]
 [ 0.17205649  0.1045921   0.17405278]]


### 6.Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.
hint:
> use [L1 normalization](https://blog.enterprisedna.co/normalize-numpy-array/)

In [13]:
# creat a 5x5 matrix
arr = np.random.rand(5, 5)

# Calculate l1 normaliztion
# matrix / l1 norm
# l1 norm = sum of the absolute values of the array elements(sum(|arr|))
# can use np.linalg.norm()
l1_norm = np.linalg.norm(arr, axis=1, keepdims=True)
norm_arr = arr / l1_norm

# print original and normalized matirx
print(f"Original array:\n{arr}\n")
print(f"L1 normalized matrix:\n{norm_arr}")

Original array:
[[0.03455846 0.73036147 0.12929552 0.55036615 0.69009192]
 [0.24046992 0.18805615 0.80681237 0.97400773 0.20418483]
 [0.59712666 0.61884203 0.55613958 0.24082882 0.44305432]
 [0.2733629  0.99139253 0.68302656 0.53108198 0.54431111]
 [0.32139671 0.74241007 0.11301737 0.24880235 0.21769622]]

L1 normalized matrix:
[[0.0299607  0.63319202 0.11209366 0.47714381 0.59828005]
 [0.18258755 0.14279005 0.61260839 0.73955895 0.15503647]
 [0.52308889 0.54211177 0.48718379 0.21096844 0.38811998]
 [0.18852908 0.68372966 0.47106015 0.36626915 0.37539283]
 [0.36472095 0.84248685 0.1282521  0.28234087 0.24704164]]


### 7.Write a NumPy program to create a 3x3x3 array with random values and find the sum along the last axis.

In [14]:
# creat a 3x3x3 array 
arr = np.random.rand(3, 3, 3)

# sum of arrays element
# use np.sum()
sum_arr = np.sum(arr, axis=2)

# print original and normalized matirx
print(f"Original array:\n{arr}\n")
print(f"Sum along the last axis:\n{sum_arr}")

Original array:
[[[0.84665984 0.39710606 0.59823046]
  [0.10984816 0.81177807 0.65334799]
  [0.81328866 0.31665518 0.22805513]]

 [[0.95350035 0.59171689 0.46996177]
  [0.35241027 0.42523891 0.33126815]
  [0.96616743 0.92510163 0.51219584]]

 [[0.62841371 0.46559338 0.15042922]
  [0.70692414 0.12770214 0.2844258 ]
  [0.55749369 0.44046016 0.06543778]]]

Sum along the last axis:
[[1.84199637 1.57497422 1.35799898]
 [2.01517901 1.10891733 2.4034649 ]
 [1.24443632 1.11905208 1.06339162]]


### 8.Write a NumPy program to create a 5x5 array with random values and sort each row.

In [15]:
# creat a 5x5 array 
arr = np.random.rand(5, 5)

# sorting
sorted_arr = np.sort(arr)

# print original and sorted matirx
print(f"Original array:\n{arr}\n")
print(f"sorted matrix:\n{sorted_arr}")

Original array:
[[0.2095608  0.875306   0.14749504 0.98028671 0.90058405]
 [0.43632091 0.57102217 0.0830769  0.17291587 0.48674099]
 [0.2303871  0.51594364 0.73000487 0.90670764 0.42647388]
 [0.01175666 0.62775987 0.1604511  0.51754948 0.78959329]
 [0.74755965 0.36590009 0.19920822 0.18922082 0.83674179]]

sorted matrix:
[[0.14749504 0.2095608  0.875306   0.90058405 0.98028671]
 [0.0830769  0.17291587 0.43632091 0.48674099 0.57102217]
 [0.2303871  0.42647388 0.51594364 0.73000487 0.90670764]
 [0.01175666 0.1604511  0.51754948 0.62775987 0.78959329]
 [0.18922082 0.19920822 0.36590009 0.74755965 0.83674179]]


### 9.Write a NumPy program to create a 5x5 array with random values and sort each column.

In [16]:
# creat a 5x5 array 
arr = np.random.rand(5, 5)

# sorting
sorted_arr = np.sort(arr, axis=0)

# print original and sorted matrix
print(f"Original array:\n{arr}\n")
print(f"sorted matrix:\n{sorted_arr}")

Original array:
[[0.20646877 0.96767984 0.25917103 0.78062724 0.2288664 ]
 [0.99045527 0.5982985  0.58561837 0.69396926 0.79870447]
 [0.9187208  0.12887276 0.75071767 0.8882211  0.12101039]
 [0.81494815 0.85661897 0.10400253 0.14204699 0.54489069]
 [0.18795562 0.40458373 0.4345952  0.69166862 0.77570937]]

sorted matrix:
[[0.18795562 0.12887276 0.10400253 0.14204699 0.12101039]
 [0.20646877 0.40458373 0.25917103 0.69166862 0.2288664 ]
 [0.81494815 0.5982985  0.4345952  0.69396926 0.54489069]
 [0.9187208  0.85661897 0.58561837 0.78062724 0.77570937]
 [0.99045527 0.96767984 0.75071767 0.8882211  0.79870447]]


### 10.Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row.

In [17]:
## creat a 5x5 array 
arr = np.random.rand(5, 5)

# find second largest
# can use np.partition
second_largest = np.partition(arr, -2)[:, -2]

# print original and second largest value in each row
print(f"Original array:\n{arr}\n")
print(f"Second largest value in each row:\n{second_largest}")

Original array:
[[0.33792743 0.94910038 0.10864219 0.65286245 0.03686088]
 [0.51778492 0.68751792 0.98234616 0.91777894 0.87653166]
 [0.02628658 0.22771743 0.0204077  0.08168265 0.46166627]
 [0.17424505 0.87257586 0.9998047  0.92697682 0.66734277]
 [0.76283779 0.32271529 0.3546402  0.5284363  0.67049636]]

Second largest value in each row:
[0.65286245 0.91777894 0.22771743 0.92697682 0.67049636]


### 11.Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.

In [18]:
# creat a 5x5 array 
arr = np.random.rand(5, 5)

# find second largest
# can use np.partition
second_largest = np.partition(arr, -2, axis=0)[-2, :]

# print original and second largest value in each column
print(f"Original array:\n{arr}\n")
print(f"Second largest value in each column:\n{second_largest}")

Original array:
[[0.16219815 0.97122728 0.82741379 0.43226576 0.45948447]
 [0.70782461 0.33289125 0.01609497 0.81131568 0.78531809]
 [0.23820362 0.0023235  0.30351081 0.76474893 0.41976872]
 [0.12555465 0.87242245 0.98535064 0.84856396 0.4236814 ]
 [0.10180947 0.4497356  0.03959112 0.76381141 0.64078539]]

Second largest value in each column:
[0.23820362 0.87242245 0.82741379 0.81131568 0.64078539]


### 12.Write a NumPy program to create a 5x5 array with random values and replace the maximum value with 0.

In [19]:
arr = np.random.rand(5, 5)

print(f"Original array:\n{arr}\n")

max_value = arr.max()
arr[arr == max_value] = 0

print(f"Said array after replacing the maximum value with 0:\n{arr}")

Original array:
[[0.05752661 0.56796214 0.96140629 0.41627702 0.86931655]
 [0.7964795  0.30257078 0.19498607 0.45354224 0.77634006]
 [0.1045795  0.52917586 0.90091878 0.93085523 0.23874777]
 [0.86245441 0.32584025 0.82168211 0.62178477 0.47687053]
 [0.23316613 0.44070008 0.83821743 0.50110567 0.72563718]]

Said array after replacing the maximum value with 0:
[[0.05752661 0.56796214 0.         0.41627702 0.86931655]
 [0.7964795  0.30257078 0.19498607 0.45354224 0.77634006]
 [0.1045795  0.52917586 0.90091878 0.93085523 0.23874777]
 [0.86245441 0.32584025 0.82168211 0.62178477 0.47687053]
 [0.23316613 0.44070008 0.83821743 0.50110567 0.72563718]]


###  13.Write a NumPy program to create a 5x5 array with random values and calculate the exponential of each element

In [20]:
# creat 5x5 array
arr = np.random.rand(5, 5)

# calculate exponential of each element
exp_arr = np.exp(arr)

print(f"Original array:\n{arr}\n")
print(f"Exponential of each element array:\n{exp_arr}")


Original array:
[[0.60985567 0.52969386 0.13099335 0.82302164 0.34328786]
 [0.89690374 0.2323342  0.76775237 0.4772527  0.24641588]
 [0.27623228 0.64657793 0.60922294 0.70988913 0.7812456 ]
 [0.42134526 0.77249203 0.74396531 0.62596799 0.30651519]
 [0.7968641  0.91406473 0.46668834 0.90407168 0.11413393]]

Exponential of each element array:
[[1.84016579 1.69841228 1.13996021 2.27737084 1.40957447]
 [2.45199931 1.26154126 2.15491736 1.61164066 1.27943156]
 [1.31815401 1.90899692 1.83900183 2.03376577 2.18419119]
 [1.52401037 2.16515516 2.10426304 1.87005527 1.35868211]
 [2.21857279 2.49444118 1.59470432 2.46963826 1.12090223]]


### 14.Write a NumPy program to create a 4x4 array with random values and compute the eigenvalues and eigenvectors.

In [21]:
arr = np.random.rand(4, 4)

eigenvalues, eigenvectors = np.linalg.eig(arr)
print(f"Original array:\n{arr}\n")
print(f"eigenvalues:\n{eigenvalues}\n")
print(f"eigenvectors:\n{eigenvectors}")

Original array:
[[0.82351479 0.88296222 0.78770065 0.13267827]
 [0.17617112 0.24444565 0.32697943 0.43703837]
 [0.92427253 0.86024089 0.2141761  0.11909129]
 [0.52338657 0.89020244 0.39991567 0.00371938]]

eigenvalues:
[ 1.91963121  0.22905293 -0.52124581 -0.34158241]

eigenvectors:
[[ 0.66839276  0.61547083 -0.06754581  0.52234811]
 [ 0.28666287 -0.59634408 -0.55525252 -0.28801773]
 [ 0.53670425  0.27715893  0.65135831 -0.5484644 ]
 [ 0.42781312 -0.43445635  0.51270319  0.58599065]]


### 15.Write a NumPy program to create a 6x6 array with random values and compute the inverse of the matrix.

In [22]:
arr = np.random.rand(6, 6)
inverse = np.linalg.inv(arr)

print(f"Original array:\n{arr}\n")
print(f"invers array:\n{inverse}")

Original array:
[[0.55151019 0.43880588 0.42042851 0.66133998 0.45697311 0.69025196]
 [0.52844228 0.86185622 0.8218309  0.83732318 0.27763606 0.18819273]
 [0.66478132 0.13215224 0.25936859 0.54547794 0.86883754 0.96619119]
 [0.94669292 0.70849271 0.08878944 0.19204599 0.08188505 0.25065418]
 [0.07496365 0.59903818 0.05454558 0.9145904  0.34545643 0.52072631]
 [0.4185534  0.22862107 0.98238674 0.54842766 0.67041933 0.00455979]]

invers array:
[[  9.01650873  -8.40606006  -6.51829453   2.93182138   1.72964315
    4.53339206]
 [-13.42771133  11.67487905   9.18130751  -2.25609146  -2.3162932
   -6.11171298]
 [ -1.39219858   3.66423949   1.8422158   -1.62104635  -2.10204354
   -1.67478766]
 [ 13.37881629 -12.12000255 -10.11561477   2.83792097   3.9911577
    6.60610717]
 [ -9.93670908   5.77906307   6.48923374  -0.99370009  -0.46006926
   -2.17991071]
 [ -2.61115519   4.84900792   3.6450881   -1.98209568  -2.14852931
   -3.60295973]]


### 16.Write a NumPy program to create a 4x4 array with random values and calculate the determinant.

In [23]:
arr = np.random.rand(4, 4)

determinant = np.linalg.det(arr)

print(f"Original array:\n{arr}\n")
print(f"determinant of array:\n{determinant}")

Original array:
[[0.58803514 0.86015629 0.89552534 0.37628943]
 [0.64522417 0.0778281  0.52909834 0.31168939]
 [0.09417845 0.94044083 0.80916604 0.33385952]
 [0.99596822 0.29843073 0.8661828  0.23757044]]

determinant of array:
0.029015273884979396


###  17.Write a NumPy program to create a 3x3x3 array with random values and flatten it to a 1D array.

In [24]:
arr = np.random.rand(3, 3, 3)

flatten_arr = arr.flatten()

print(f"Original array:\n{arr}\n")
print(f"flatten array:\n{flatten_arr}")

Original array:
[[[0.11883264 0.38355573 0.68686835]
  [0.98442566 0.29734226 0.10915681]
  [0.18730618 0.73407767 0.97753578]]

 [[0.28337536 0.87951905 0.88770141]
  [0.2423827  0.26744066 0.11984085]
  [0.18955062 0.83376047 0.38012229]]

 [[0.15114037 0.5102105  0.54456467]
  [0.06827245 0.93718175 0.34304179]
  [0.95715158 0.96553296 0.04139253]]]

flatten array:
[0.11883264 0.38355573 0.68686835 0.98442566 0.29734226 0.10915681
 0.18730618 0.73407767 0.97753578 0.28337536 0.87951905 0.88770141
 0.2423827  0.26744066 0.11984085 0.18955062 0.83376047 0.38012229
 0.15114037 0.5102105  0.54456467 0.06827245 0.93718175 0.34304179
 0.95715158 0.96553296 0.04139253]


### 18.Write a NumPy program to create a 5x5 array with random values and calculate the trace of the matrix.

In [25]:
arr = np.random.rand(5, 5)

trace_arr = np.trace(arr)

print(f"Original array:\n{arr}\n")
print(f"trace of array:\n{trace_arr}")

Original array:
[[0.25925732 0.32356926 0.58817012 0.68216349 0.79616319]
 [0.92888843 0.95712064 0.70064269 0.93682079 0.41302776]
 [0.56947917 0.71990263 0.39481586 0.23615679 0.24766246]
 [0.9700272  0.02345879 0.75494548 0.52748751 0.82375332]
 [0.05569091 0.39667192 0.82266985 0.61439541 0.51544737]]

trace of array:
2.6541287041874755


### 19.Write a NumPy program to create a 4x4 array with random values and extract the upper triangular part of the matrix.

In [26]:
arr = np.random.rand(4, 4)

upper_triangular = np.triu(arr)

print(f"Original array:\n{arr}\n")
print(f"upper triangular part of the matrix:\n{upper_triangular}")

Original array:
[[0.87087835 0.18106073 0.12646744 0.79158376]
 [0.52289078 0.37695651 0.00537182 0.33900615]
 [0.15097205 0.67782804 0.90694052 0.07782964]
 [0.7581085  0.76329354 0.87952739 0.96560663]]

upper triangular part of the matrix:
[[0.87087835 0.18106073 0.12646744 0.79158376]
 [0.         0.37695651 0.00537182 0.33900615]
 [0.         0.         0.90694052 0.07782964]
 [0.         0.         0.         0.96560663]]


### 20.Write a NumPy program to create a 6x6 array with random values and compute the rank of the matrix.

In [27]:
arr = np.random.rand(6, 6)

rank_arr = np.linalg.matrix_rank(arr)

print(f"Original array:\n{arr}\n")
print(f"rank of the matrix:\n{rank_arr}")

Original array:
[[0.08096262 0.30761701 0.05942188 0.67589789 0.87740098 0.41558585]
 [0.64836041 0.91501722 0.03897478 0.74212122 0.69442564 0.66600336]
 [0.0301975  0.79054637 0.63150366 0.59826563 0.1721975  0.20004653]
 [0.82522507 0.85583193 0.54566738 0.9337848  0.70683789 0.657629  ]
 [0.79926708 0.3705093  0.37108339 0.5422786  0.92602292 0.14249389]
 [0.82759143 0.56169443 0.03862626 0.1840862  0.36556573 0.6231659 ]]

rank of the matrix:
6


### 21.Write a NumPy program to create a 3x3 array with random values and compute the Frobenius norm of the matrix.

In [28]:
arr = np.random.rand(3, 3)

fro_norm = np.linalg.norm(arr, 'fro')

print(f"Original array:\n{arr}\n")
print(f"frobenius norm:\n{fro_norm}")

Original array:
[[0.84018372 0.82683901 0.26895953]
 [0.46933216 0.11805521 0.42317699]
 [0.73532311 0.78607872 0.72555068]]

frobenius norm:
1.886860557856821


### 22.Write a NumPy program to create a 5x5 array with random values and find the index of the minimum value in each row.

In [29]:
arr = np.random.rand(5, 5)

index_max = np.argmin(arr, axis=0)

print(f"Original array:\n{arr}\n")
print(f"index of the minimum value in sech row :\n{index_max}")

Original array:
[[0.28197534 0.1799042  0.38348092 0.52603933 0.40580768]
 [0.33093777 0.78329416 0.9501682  0.86371442 0.9626446 ]
 [0.28580302 0.57755851 0.85773868 0.52406804 0.05527752]
 [0.89995606 0.79535422 0.40290496 0.13984265 0.62360655]
 [0.61025105 0.61024817 0.39130757 0.72976198 0.81677274]]

index of the minimum value in sech row :
[0 0 0 3 2]


### 23.Write a NumPy program to create a 3x3 array with random values and compute the QR decomposition.

In [30]:
arr = np.random.rand(3, 3)

q, r = np.linalg.qr(arr)

print("Original Array:\n", arr)
print("Q Matrix:\n", q)
print("R Matrix:\n", r)

Original Array:
 [[0.84106034 0.89430349 0.16940862]
 [0.50610715 0.85274769 0.24079612]
 [0.66090123 0.77573273 0.32201175]]
Q Matrix:
 [[-0.71074517  0.45941502 -0.53270925]
 [-0.42769013 -0.88345614 -0.19127569]
 [-0.55850018  0.09188622  0.82439946]]
R Matrix:
 [[-1.18335007 -1.43358053 -0.4032361 ]
 [ 0.         -0.27122958 -0.1053155 ]
 [ 0.          0.          0.12916233]]


### 24.Write a NumPy program to create a 3x3 array with random values and compute the Cholesky decomposition.

In [31]:
arr = np.random.random((5, 5))

# Make the array symmetric and positive-definite for Cholesky decomposition
symmetric_arr = np.dot(arr, arr.T)
# Compute the Cholesky decomposition
cholesky = np.linalg.cholesky(symmetric_arr)

print(f"Original array:\n{arr}\n")
print(f"Symmetric Positive-Definite Array:\n{symmetric_arr}\n")
print(f"cholesky decopomposition\n{symmetric_arr}")

Original array:
[[0.71654692 0.35029697 0.93152857 0.03698826 0.45630715]
 [0.55129079 0.9166809  0.79573304 0.75351103 0.38610885]
 [0.71032842 0.93303757 0.50313766 0.63965623 0.68384526]
 [0.71791926 0.60020276 0.95510921 0.03462126 0.36601368]
 [0.89229703 0.25780468 0.63040361 0.05831441 0.74975306]]

Symmetric Positive-Definite Array:
[[1.71347728 1.66143961 1.64021423 1.7826788  1.66119449]
 [1.66143961 2.49427538 2.39328522 1.87339725 1.56329958]
 [1.64021423 2.39328522 2.5050775  1.82296401 1.74156144]
 [1.7826788  1.87339725 1.82296401 1.92304966 1.67387539]
 [1.66119449 1.56329958 1.74156144 1.67387539 1.82559618]]

cholesky decopomposition
[[1.71347728 1.66143961 1.64021423 1.7826788  1.66119449]
 [1.66143961 2.49427538 2.39328522 1.87339725 1.56329958]
 [1.64021423 2.39328522 2.5050775  1.82296401 1.74156144]
 [1.7826788  1.87339725 1.82296401 1.92304966 1.67387539]
 [1.66119449 1.56329958 1.74156144 1.67387539 1.82559618]]


### 25.Write a NumPy program to create a 4x4 array with random values and swap the first and last rows.

In [32]:
arr = np.random.rand(4, 4)

print(f"Original array:\n{arr}\n")

arr[[0,-1]] = arr[[-1,0]]
print(f"Array after swapping first and last rows:\n{arr}")

Original array:
[[0.5694331  0.46807357 0.66649254 0.23859766]
 [0.15386927 0.42418389 0.74452377 0.62608889]
 [0.06671334 0.40321984 0.23621149 0.99446895]
 [0.08375982 0.94017785 0.93130997 0.28203846]]

Array after swapping first and last rows:
[[0.08375982 0.94017785 0.93130997 0.28203846]
 [0.15386927 0.42418389 0.74452377 0.62608889]
 [0.06671334 0.40321984 0.23621149 0.99446895]
 [0.5694331  0.46807357 0.66649254 0.23859766]]


### 26.Write a NumPy program to create a 4x4 array with random values and rotate the array 90 degrees counterclockwise.

In [33]:
arr = np.random.rand(4, 4)

rotated_arr = np.rot90(arr)

print(f"Original array:\n{arr}\n")
print(f"rotated array:\n{rotated_arr}")

Original array:
[[0.67505402 0.59073423 0.33587028 0.0098932 ]
 [0.39149498 0.40776905 0.26037831 0.18392826]
 [0.28748255 0.22913088 0.77951501 0.11428585]
 [0.61242075 0.83805412 0.13757458 0.63821949]]

rotated array:
[[0.0098932  0.18392826 0.11428585 0.63821949]
 [0.33587028 0.26037831 0.77951501 0.13757458]
 [0.59073423 0.40776905 0.22913088 0.83805412]
 [0.67505402 0.39149498 0.28748255 0.61242075]]


###  27.Write a NumPy program to create a 4x4 array with random values and shift all elements one position to the right.

In [34]:
arr = np.random.random((4, 4))

shifted_arr = np.roll(arr, shift=1, axis=1)

print(f"Original array:\n{arr}\n")
print(f"shifted array:\n{shifted_arr}")

Original array:
[[0.88856394 0.48872088 0.25090498 0.54227553]
 [0.06487722 0.06257335 0.55174492 0.82672055]
 [0.93509714 0.16861567 0.36908846 0.77039768]
 [0.18782145 0.38643785 0.89562499 0.09678191]]

shifted array:
[[0.54227553 0.88856394 0.48872088 0.25090498]
 [0.82672055 0.06487722 0.06257335 0.55174492]
 [0.77039768 0.93509714 0.16861567 0.36908846]
 [0.09678191 0.18782145 0.38643785 0.89562499]]


###  28.Write a NumPy program to create a 3x3 array with random values and calculate the pairwise Euclidean distance between each pair of rows.
hint:
> use sipy library

In [35]:
from scipy.spatial import distance

array = np.random.random((3, 3))

# Calculate pairwise Euclidean distances between each pair of rows
pairwise_distances = distance.cdist(array, array, 'euclidean')

print("Original Array:\n", array)
print("Pairwise Euclidean distances between each pair of rows:\n", pairwise_distances)

Original Array:
 [[0.05294323 0.00930488 0.1139951 ]
 [0.43073085 0.82603125 0.00268468]
 [0.88240643 0.61733432 0.71578445]]
Pairwise Euclidean distances between each pair of rows:
 [[0.         0.90672788 1.19157854]
 [0.90672788 0.         0.86952661]
 [1.19157854 0.86952661 0.        ]]
